import { AppShell } from "@/components/AppShell";
import { PendingQueueStatus } from "@/components/PendingQueueStatus";
import { DeletePendingCvButton, RecentProcessedCandidates } from "@/components/ReviewActions";
import { createClient } from "@/lib/supabase/server";
import { CheckCircle2, ListRestart } from "lucide-react";

export default async function PendingPage(){
  const supabase=await createClient();const [{data},{data:recentData}]=await Promise.all([supabase.from("pending_cv_imports").select("id,filename,subject,sender,received_at,status,last_error").order("received_at",{ascending:false}).limit(1000),supabase.from("candidates").select("id,first_name,last_name,latest_cv_filename,updated_at").order("updated_at",{ascending:false}).limit(50)]);const rows=data??[];const recent=(recentData??[]).map(row=>({id:row.id,name:`${row.first_name} ${row.last_name}`,filename:row.latest_cv_filename??"",updatedAt:row.updated_at}));
  const waiting=rows.filter(row=>row.status==="pending").length;
  return <AppShell title="Da elaborare" eyebrow="Coda CV" active="Da elaborare"><section className="queue-summary panel"><span className="queue-icon"><ListRestart/></span><div><h2>{rows.length}</h2><p>CV già acquisiti da Gmail e analizzati automaticamente da Qwen. Non serve avviare manualmente ogni gruppo.</p></div></section><PendingQueueStatus initialCount={waiting}/><section className="panel queue-panel"><div className="panel-head"><div><p className="eyebrow">In attesa e da rivedere</p><h3>Curriculum da elaborare</h3></div></div>{rows.length?<div className="queue-list pending-review-list">{rows.map(row=><article key={row.id}><span className="candidate-avatar lavender"><ListRestart size={17}/></span><div><strong>{row.filename}</strong><p>{row.subject||"Senza oggetto"} · {row.sender||"Mittente non indicato"}</p>{row.status==="failed"&&<small>{row.last_error||"Elaborazione non riuscita"}</small>}</div>{row.status==="failed"&&<DeletePendingCvButton rowId={row.id} filename={row.filename}/>}</article>)}</div>:<div className="queue-empty"><CheckCircle2/><strong>Nessun CV in attesa</strong><p>La coda di elaborazione è vuota.</p></div>}</section><section className="panel queue-panel recent-panel"><div className="panel-head"><div><p className="eyebrow">Controllo archivio</p><h3>Ultimi elaborati</h3></div><span className="soft-count">ultimi {recent.length}</span></div><p className="section-help">Seleziona solo i profili che vuoi rimuovere. L'ordine parte dall'ultima elaborazione o modifica.</p><RecentProcessedCandidates rows={recent}/></section></AppShell>
}
