import Link from "next/link";
import { ArrowRight, CheckCircle2, CircleAlert, FileQuestion } from "lucide-react";
import { AppShell } from "@/components/AppShell";
import { CandidatePhoto, QuickGenderButtons } from "@/components/CandidateActions";
import { createClient } from "@/lib/supabase/server";

export default async function IncompletePage(){
  const supabase=await createClient();const {data}=await supabase.from("candidates").select("id,first_name,last_name,birth_year,birth_place,declared_gender,email,phone,city,bio,needs_review,extraction_confidence").order("updated_at",{ascending:false}).limit(1000);
  const people=(data??[]).map(person=>{const missing=[];if(!person.birth_year)missing.push("anno di nascita");if(!person.birth_place)missing.push("luogo di nascita");if(!person.declared_gender)missing.push("sesso non dichiarato");if(!person.email)missing.push("email");if(!person.phone)missing.push("telefono");if(!person.city)missing.push("città");if(!person.bio)missing.push("bio");if(person.needs_review)missing.push("estrazione da verificare");return{...person,missing}}).filter(person=>person.missing.length>0);
  return <AppShell title="Dati incompleti" eyebrow="Revisione necessaria" active="Dati incompleti"><section className="queue-summary panel"><span className="queue-icon"><FileQuestion/></span><div><h2>{people.length}</h2><p>Profili con campi mancanti o informazioni che richiedono una verifica.</p></div></section><section className="panel queue-panel"><div className="panel-head"><div><p className="eyebrow">Elementi da gestire</p><h3>Dati incompleti</h3></div><span className="soft-count">{people.length} profili</span></div>{people.length?<div className="queue-list">{people.map(person=>{const initials=`${person.first_name?.[0]??""}${person.last_name?.[0]??""}`.toUpperCase();return <article key={person.id}><CandidatePhoto candidateId={person.id} initials={initials}/><div><strong>{person.first_name} {person.last_name}</strong><p>Mancano: {person.missing.join(", ")}</p>{!person.declared_gender&&<QuickGenderButtons candidateId={person.id}/>}</div><span className={`priority ${person.missing.length>=4?"priority-alta":"priority-media"}`}><CircleAlert size={12}/>{person.missing.length} campi</span><Link href={`/candidati/${person.id}?edit=1`} className="text-link">Completa scheda<ArrowRight size={15}/></Link></article>})}</div>:<div className="queue-empty"><CheckCircle2/><strong>Tutte le schede sono complete</strong><p>Non risultano informazioni mancanti.</p></div>}</section><div className="queue-tip"><CheckCircle2/><div><strong>Conferma manuale</strong><p>Quando il sesso non è presente nel CV puoi inserirlo rapidamente; il sistema non lo deduce dal nome.</p></div></div></AppShell>
}
