"use client";
import { useState } from "react";
import { AppShell } from "@/components/AppShell";
import { CheckCircle2, FileSearch, Inbox, LoaderCircle, Mail, Play, RotateCcw, ShieldCheck, Sparkles } from "lucide-react";

export default function ImportPage(){const [running,setRunning]=useState(false);return <AppShell title="Importa curriculum" active="Importa CV">
  <section className="import-hero panel"><span className="import-icon"><Inbox/></span><div><p className="eyebrow">Sincronizzazione manuale</p><h2>Importa i nuovi CV da Gmail</h2><p>Analizzeremo soltanto le email non ancora elaborate. I duplicati verranno riconosciuti automaticamente.</p></div><button className="primary-button purple-button" onClick={()=>setRunning(!running)}>{running?<><LoaderCircle className="spin"/> Elaborazione...</>:<><Play/> Avvia importazione</>}</button></section>
  <section className="import-grid"><article className="panel import-process"><div className="panel-head"><div><p className="eyebrow">Come funziona</p><h3>Processo di importazione</h3></div></div>{[[Mail,"Legge le nuove email","Ricerca solo i messaggi successivi all’ultima importazione."],[FileSearch,"Estrae i dati","Legge PDF e Word e struttura esperienze, istruzione e contatti."],[Sparkles,"Organizza con Gemini","Compila le card e segnala i campi che richiedono verifica."],[CheckCircle2,"Salva senza duplicati","Aggiorna la scheda esistente quando trova un CV più recente."]].map(([Icon,title,copy],i)=>{const I=Icon as typeof Mail;return <div className="process-step" key={String(title)}><span>{i+1}</span><i><I size={20}/></i><div><strong>{String(title)}</strong><p>{String(copy)}</p></div></div>})}</article>
  <aside><article className="panel sync-card"><p className="eyebrow">Ultima attività</p><h3>Sincronizzazione</h3><div className="sync-stat"><span>Ultima importazione</span><b>Non ancora eseguita</b></div><div className="sync-stat"><span>Email elaborate</span><b>0</b></div><div className="sync-stat"><span>Errori da riprovare</span><b>0</b></div><button className="secondary-button full"><RotateCcw size={15}/> Controlla collegamento</button></article><article className="privacy-note"><ShieldCheck/><div><strong>Elaborazione protetta</strong><p>I file temporanei vengono rimossi al termine e il CV resta archiviato in Gmail.</p></div></article></aside></section>
</AppShell>}
