"use client";
import { useCallback, useEffect, useState } from "react";
import { AppShell } from "@/components/AppShell";
import { CheckCircle2, FileSearch, Inbox, LoaderCircle, Mail, Play, ShieldCheck, Sparkles, Square } from "lucide-react";

type Job={id:string;status:string;found_count:number;duplicate_count:number;failed_count:number;created_at:string;completed_at:string|null};
type State={job:Job|null;progress?:{estimated_total?:number;last_batch_queued?:number};pending:number};
const labels:Record<string,string>={background_requested:"In attesa del worker locale",background_running:"Importazione in corso",background_completed:"Importazione completata",background_failed:"Importazione interrotta",background_cancelled:"Importazione annullata"};

export default function ImportPage(){
  const [state,setState]=useState<State|null>(null);const [loading,setLoading]=useState(true);const [error,setError]=useState("");
  async function readResponse(response:Response){const text=await response.text();try{return JSON.parse(text)}catch{throw new Error(text||`Risposta non valida dal server (${response.status})`)}}
  const refresh=useCallback(async()=>{try{const response=await fetch("/api/imports/background",{cache:"no-store"});const body=await readResponse(response);if(!response.ok)throw new Error(body.detail??"Stato non disponibile");setState(body);setError("")}catch(cause){setError(cause instanceof Error?cause.message:"Stato non disponibile")}finally{setLoading(false)}},[]);
  useEffect(()=>{refresh();const timer=window.setInterval(refresh,3000);return()=>window.clearInterval(timer)},[refresh]);
  async function action(method:"POST"|"DELETE"){setLoading(true);setError("");try{const response=await fetch("/api/imports/background",{method});const body=await readResponse(response);if(!response.ok)throw new Error(body.detail??"Operazione non riuscita");await refresh()}catch(cause){setError(cause instanceof Error?cause.message:"Operazione non riuscita")}finally{setLoading(false)}}
  const job=state?.job;const running=job?.status==="background_requested"||job?.status==="background_running";const complete=job?.status==="background_completed";const scanned=job?.found_count??0;const estimated=Math.max(state?.progress?.estimated_total??0,scanned);const progress=complete?100:estimated?Math.min(99,Math.round(scanned/estimated*100)):0;
  return <AppShell title="Importa curriculum" active="Importa CV">
    <section className="import-hero panel"><span className="import-icon"><Inbox/></span><div><p className="eyebrow">Importazione in background</p><h2>Importa senza fermare il tuo lavoro</h2><p>Avvia una volta il processo, poi consulta candidati e altre sezioni: il worker continua autonomamente.</p></div>{running?<button className="secondary-button stop-import" onClick={()=>action("DELETE")} disabled={loading}><Square size={15}/> Interrompi</button>:<button className="primary-button purple-button" onClick={()=>action("POST")} disabled={loading}>{loading?<LoaderCircle className="spin"/>:<Play/>} Avvia importazione</button>}</section>
    <section className="panel automatic-progress"><div className="panel-head"><div><p className="eyebrow">Stato persistente</p><h3>{loading&&!state?"Caricamento…":job?labels[job.status]??job.status:"Pronto per iniziare"}</h3></div><strong className="progress-percent">{progress}%</strong></div><div className="overall-progress"><i style={{width:`${progress}%`}}/></div><div className="progress-metrics"><span><b>{scanned}</b>Email controllate</span><span><b>{estimated||"—"}</b>Email stimate</span><span><b>{state?.pending??0}</b>CV da elaborare</span><span><b>{job?.duplicate_count??0}</b>Già presenti</span></div>{error&&<div className="import-feedback import-error"><strong>Operazione non disponibile</strong><span>{error}</span></div>}{running&&<div className="import-feedback"><strong>Puoi cambiare pagina</strong><span>Importazione Gmail e analisi Qwen proseguiranno in background.</span></div>}{complete&&<div className="import-complete wide-complete"><CheckCircle2/> Tutte le email individuate sono state controllate.</div>}</section>
    <section className="import-grid"><article className="panel import-process"><div className="panel-head"><div><p className="eyebrow">Lavori paralleli</p><h3>Cosa succede in background</h3></div></div>{[[Mail,"Importazione Gmail","Aggiunge progressivamente i CV alla coda."],[Sparkles,"Analisi locale Qwen","Elabora fino a tre CV mentre l’import continua."],[FileSearch,"Archivio sempre disponibile","Puoi cercare, filtrare e modificare i candidati."],[CheckCircle2,"Avanzamento salvato","Chiudere o cambiare pagina non azzera il processo."]].map(([Icon,title,copy],i)=>{const I=Icon as typeof Mail;return <div className="process-step" key={String(title)}><span>{i+1}</span><i><I size={20}/></i><div><strong>{String(title)}</strong><p>{String(copy)}</p></div></div>})}</article><aside><article className="privacy-note"><ShieldCheck/><div><strong>Il PC deve restare acceso</strong><p>Ollama e il worker locale devono essere attivi per importare e analizzare. L’interfaccia può invece essere chiusa o usata da un altro dispositivo.</p></div></article></aside></section>
  </AppShell>
}
