import { notFound } from "next/navigation";
import { AppShell } from "@/components/AppShell";
import { CandidateClassification, CandidateEditor, CandidatePhoto, CvButton, DeleteCandidateButton, NoteForm, RetryPhotoButton, StatusControl } from "@/components/CandidateActions";
import { ResumeSectionEditor } from "@/components/ResumeSectionEditor";
import { createClient } from "@/lib/supabase/server";
import { BriefcaseBusiness, CalendarDays, GraduationCap, Mail, MapPin, Phone, Sparkles, UserRound } from "lucide-react";
const genderLabels:Record<string,string>={female:"Donna",male:"Uomo",other:"Altro"};
const shortDate=(value?:string|null)=>value?new Intl.DateTimeFormat("it-IT",{month:"short",year:"numeric"}).format(new Date(value)):"—";
const fullDate=(value?:string|null)=>value?new Intl.DateTimeFormat("it-IT",{day:"2-digit",month:"long",year:"numeric",hour:"2-digit",minute:"2-digit"}).format(new Date(value)):"—";
export default async function CandidatePage({params,searchParams}:{params:Promise<{id:string}>;searchParams:Promise<{edit?:string}>}){
 const {id}=await params;const query=await searchParams;const supabase=await createClient();const {data,error}=await supabase.from("candidates").select("*,experiences(*),education(*),skills(*),candidate_notes(id,body,created_at,pinned)").eq("id",id).single();if(error||!data)notFound();const candidate=data as any;const experiences=[...(candidate.experiences??[])].sort((a:any,b:any)=>a.sort_order-b.sort_order);const education=[...(candidate.education??[])].sort((a:any,b:any)=>a.sort_order-b.sort_order);const skills=candidate.skills??[];const notes=[...(candidate.candidate_notes??[])].sort((a:any,b:any)=>new Date(b.created_at).getTime()-new Date(a.created_at).getTime());const name=`${candidate.first_name} ${candidate.last_name}`;const initials=`${candidate.first_name?.[0]??""}${candidate.last_name?.[0]??""}`.toUpperCase();const role=experiences[0]?.role??"Profilo da definire";
 return <AppShell title="Profilo candidato" active="Candidati">
  <section className="profile-hero panel"><CandidatePhoto candidateId={id} initials={initials} large/><div className="profile-title"><span className="soft-label purple-soft">{candidate.needs_review?"Da verificare":"Dati estratti"}</span><h2>{name}</h2><p><MapPin size={14}/> {candidate.city??"Località non indicata"} · {role}</p></div><div className="profile-actions"><RetryPhotoButton candidateId={id}/><CandidateEditor candidateId={id} candidate={candidate} startOpen={query.edit==="1"}/><CvButton candidateId={id}/></div></section>
  <section className="profile-layout"><div className="profile-main">
   <article className="panel info-card"><div className="panel-head"><div><p className="eyebrow">Presentazione</p><h3>Bio</h3></div>{candidate.bio_source==="ai_summary"&&<span className="ai-label"><Sparkles size={12}/> Sintesi AI</span>}</div><p className="bio-copy">{candidate.bio||"Nessuna presentazione disponibile nel curriculum."}</p></article>
   <article className="panel info-card"><div className="panel-head"><div><p className="eyebrow">Percorso</p><h3>Esperienze professionali</h3></div><ResumeSectionEditor candidateId={id} kind="experiences" rows={experiences}/></div>{experiences.length?<div className="timeline">{experiences.map((item:any,index:number)=><div className="timeline-item" key={item.id}><span className={`time-icon ${index%2?"pink":""}`}><BriefcaseBusiness size={17}/></span><div><strong>{item.role}</strong><p>{[item.company,item.location].filter(Boolean).join(" · ")||"Azienda non indicata"}</p><small>{shortDate(item.start_date)} — {item.is_current?"oggi":shortDate(item.end_date)}</small>{item.description&&<p className="experience-copy">{item.description}</p>}</div></div>)}</div>:<p className="empty-copy">Nessuna esperienza estratta.</p>}</article>
   <article className="panel info-card"><div className="panel-head"><div><p className="eyebrow">Formazione</p><h3>Istruzione</h3></div><ResumeSectionEditor candidateId={id} kind="education" rows={education}/></div>{education.length?<div className="education-list">{education.map((item:any)=><div className="education" key={item.id}><span className="time-icon green"><GraduationCap size={18}/></span><div><strong>{item.qualification}</strong><p>{[item.institution,item.field_of_study].filter(Boolean).join(" · ")}</p><small>{item.start_year||"—"} — {item.end_year||"—"}</small></div></div>)}</div>:<p className="empty-copy">Nessun percorso di istruzione estratto.</p>}</article>
   <article className="panel info-card notes-card"><div className="panel-head"><div><p className="eyebrow">Solo per uso interno</p><h3>Note sul candidato</h3></div></div>{notes.length>0&&<div className="saved-notes">{notes.map((note:any)=><div key={note.id}><p>{note.body}</p><small>{fullDate(note.created_at)}</small></div>)}</div>}<NoteForm candidateId={id}/></article>
  </div><aside className="profile-side">
   <article className="panel status-card"><p className="eyebrow">Candidatura</p><h3>Stato attuale</h3><StatusControl candidateId={id} value={candidate.status}/><div className="status-history"><p><i/><span><b>CV aggiornato</b><small>{fullDate(candidate.latest_cv_received_at)}</small></span></p><p><i/><span><b>Profilo creato</b><small>{fullDate(candidate.created_at)}</small></span></p></div></article>
   <article className="panel detail-card"><p className="eyebrow">Smistamento</p><h3>Categoria professionale</h3><CandidateClassification candidateId={id} category={candidate.job_category} protectedCategory={Boolean(candidate.protected_category)}/></article>
   <article className="panel detail-card"><p className="eyebrow">Informazioni</p><h3>Contatti e dettagli</h3><ul><li><Mail/><span>Email<b>{candidate.email||"Non indicata"}</b></span></li><li><Phone/><span>Telefono<b>{candidate.phone||"Non indicato"}</b></span></li><li><CalendarDays/><span>Anno di nascita<b>{candidate.birth_year||"Non indicato"}</b></span></li><li><MapPin/><span>Luogo di nascita<b>{candidate.birth_place||"Non indicato"}</b></span></li><li><UserRound/><span>Sesso dichiarato<b>{genderLabels[candidate.declared_gender]||"Non dichiarato"}</b></span></li></ul></article>
   <article className="panel skills-card"><div className="panel-head"><div><p className="eyebrow">Dal curriculum</p><h3>Competenze</h3></div><ResumeSectionEditor candidateId={id} kind="skills" rows={skills}/></div><div>{skills.length?skills.map((skill:any)=><span key={skill.id}>{skill.name}</span>):<p className="empty-copy">Nessuna competenza estratta.</p>}</div></article>
   <article className="panel retention-card"><p className="eyebrow">Conservazione</p><h3>Scadenza CV</h3><p>Il collegamento a questo curriculum sarà mantenuto fino al <b>{candidate.expires_at?new Intl.DateTimeFormat("it-IT",{day:"2-digit",month:"long",year:"numeric"}).format(new Date(candidate.expires_at)):"—"}</b>.</p><DeleteCandidateButton candidateId={id} name={name}/></article>
  </aside></section>
 </AppShell>;
}
