"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";
import { Check, LoaderCircle, Pencil, Plus, Trash2, X } from "lucide-react";
import { createClient } from "@/lib/supabase/client";
type Kind="experiences"|"education"|"skills"; type Row=Record<string,unknown>;
const fields:Record<Kind,{key:string;label:string;type?:string;wide?:boolean}[]>={experiences:[{key:"role",label:"Ruolo"},{key:"company",label:"Azienda"},{key:"location",label:"Località"},{key:"start_date",label:"Data inizio",type:"date"},{key:"end_date",label:"Data fine",type:"date"},{key:"description",label:"Descrizione",wide:true}],education:[{key:"qualification",label:"Titolo di studio"},{key:"institution",label:"Istituto"},{key:"field_of_study",label:"Ambito"},{key:"start_year",label:"Anno inizio",type:"number"},{key:"end_year",label:"Anno fine",type:"number"}],skills:[{key:"name",label:"Competenza"},{key:"category",label:"Categoria"},{key:"level",label:"Livello"}]};
const empty:Record<Kind,Row>={experiences:{role:"",company:"",location:"",start_date:"",end_date:"",description:"",is_current:false},education:{qualification:"",institution:"",field_of_study:"",start_year:"",end_year:""},skills:{name:"",category:"",level:""}};
export function ResumeSectionEditor({candidateId,kind,rows}:{candidateId:string;kind:Kind;rows:Row[]}){const router=useRouter();const [open,setOpen]=useState(false),[items,setItems]=useState<Row[]>(rows.map(({id,candidate_id,...row})=>row)),[saving,setSaving]=useState(false),[error,setError]=useState("");const set=(index:number,key:string,value:unknown)=>setItems(current=>current.map((row,i)=>i===index?{...row,[key]:value}:row));async function save(){setSaving(true);setError("");const supabase=createClient();const removed=await supabase.from(kind).delete().eq("candidate_id",candidateId);if(removed.error){setError("Salvataggio non riuscito");setSaving(false);return}const required=kind==="experiences"?"role":kind==="education"?"qualification":"name";const clean=items.filter(row=>String(row[required]??"").trim()).map((row,index)=>{const normalized=Object.fromEntries(Object.entries(row).map(([key,value])=>[key,value===""?null:value]));return{...normalized,candidate_id:candidateId,...(kind!=="skills"?{sort_order:index}:{})}});if(clean.length&&(await supabase.from(kind).insert(clean)).error){setError("Alcuni dati non sono stati salvati");setSaving(false);return}setSaving(false);setOpen(false);router.refresh()}return <><button className="round-add" onClick={()=>setOpen(true)} aria-label="Modifica sezione"><Pencil size={15}/></button>{open&&<section className="candidate-editor panel"><div className="panel-head"><div><p className="eyebrow">Modifica curriculum</p><h3>{kind==="experiences"?"Esperienze professionali":kind==="education"?"Istruzione":"Competenze"}</h3></div><button className="round-add" onClick={()=>setOpen(false)}><X size={17}/></button></div><div className="resume-editor-list">{items.map((row,index)=><div className="resume-editor-row" key={index}><div className="editor-grid">{fields[kind].map(field=><label className={field.wide?"editor-wide":""} key={field.key}>{field.label}{field.wide?<textarea value={String(row[field.key]??"")} onChange={e=>set(index,field.key,e.target.value)}/>:<input type={field.type??"text"} value={String(row[field.key]??"")} onChange={e=>set(index,field.key,e.target.value)}/>}</label>)}{kind==="experiences"&&<label className="check-label"><input type="checkbox" checked={Boolean(row.is_current)} onChange={e=>set(index,"is_current",e.target.checked)}/> Impiego attuale</label>}</div><button className="icon-danger" onClick={()=>setItems(current=>current.filter((_,i)=>i!==index))} aria-label="Rimuovi"><Trash2 size={15}/></button></div>)}</div><button className="secondary-button" onClick={()=>setItems(current=>[...current,{...empty[kind]}])}><Plus size={15}/> Aggiungi</button>{error&&<p className="form-error">{error}</p>}<div className="editor-actions"><button className="secondary-button" onClick={()=>setOpen(false)}>Annulla</button><button className="primary-button purple-button" onClick={save} disabled={saving}>{saving?<LoaderCircle className="spin" size={15}/>:<Check size={15}/>} Salva</button></div></section>}</>}
