import { AppShell } from "@/components/AppShell";
import { BriefcaseBusiness, CalendarDays, Check, ChevronDown, Download, GraduationCap, Languages, Mail, MapPin, Pencil, Phone, Plus, Sparkles } from "lucide-react";

export default function CandidatePage(){return <AppShell title="Profilo candidato" active="Candidati">
  <section className="profile-hero panel"><div className="large-avatar">MR</div><div className="profile-title"><span className="soft-label purple-soft">Candidatura aggiornata</span><h2>Martina Russo</h2><p><MapPin size={14}/> Milano · Addetta vendite</p></div><div className="profile-actions"><button className="secondary-button"><Pencil size={16}/> Modifica</button><button className="primary-button purple-button"><Download size={16}/> Apri CV</button></div></section>
  <section className="profile-layout"><div className="profile-main">
    <article className="panel info-card"><div className="panel-head"><div><p className="eyebrow">Presentazione</p><h3>Bio</h3></div><span className="ai-label"><Sparkles size={12}/> Sintesi AI</span></div><p className="bio-copy">Professionista della vendita con esperienza nel retail moda e nella gestione del cliente. Precisa, solare e orientata agli obiettivi, cerca un ambiente dinamico in cui valorizzare le proprie capacità relazionali.</p></article>
    <article className="panel info-card"><div className="panel-head"><div><p className="eyebrow">Percorso</p><h3>Esperienze professionali</h3></div><button className="round-add"><Plus size={17}/></button></div><div className="timeline"><div className="timeline-item"><span className="time-icon"><BriefcaseBusiness size={17}/></span><div><strong>Sales Assistant</strong><p>Moda Centro S.r.l. · Milano</p><small>Marzo 2022 — oggi · 4 anni e 5 mesi</small><ul><li>Assistenza e fidelizzazione della clientela</li><li>Allestimento e gestione del punto vendita</li></ul></div></div><div className="timeline-item"><span className="time-icon pink"><BriefcaseBusiness size={17}/></span><div><strong>Addetta alle vendite</strong><p>Urban Style · Monza</p><small>Giugno 2019 — febbraio 2022</small></div></div></div></article>
    <article className="panel info-card"><div className="panel-head"><div><p className="eyebrow">Formazione</p><h3>Istruzione</h3></div></div><div className="education"><span className="time-icon green"><GraduationCap size={18}/></span><div><strong>Diploma in Servizi commerciali</strong><p>Istituto Professionale Carlo Porta, Milano</p><small>2019</small></div></div></article>
    <article className="panel info-card notes-card"><div className="panel-head"><div><p className="eyebrow">Solo per uso interno</p><h3>Note sul candidato</h3></div></div><textarea placeholder="Aggiungi un appunto utile e pertinente alla selezione..."/><div className="note-footer"><small>Le note vengono registrate con autore e data.</small><button className="primary-button purple-button"><Check size={15}/> Salva nota</button></div></article>
  </div><aside className="profile-side">
    <article className="panel status-card"><p className="eyebrow">Candidatura</p><h3>Stato attuale</h3><button className="status-select"><span className="status-dot-big"/> Da contattare <ChevronDown size={16}/></button><div className="status-history"><p><i/><span><b>CV aggiornato</b><small>27 agosto 2026, 10:42</small></span></p><p><i/><span><b>Profilo creato</b><small>12 maggio 2026, 16:08</small></span></p></div></article>
    <article className="panel detail-card"><p className="eyebrow">Informazioni</p><h3>Contatti e dettagli</h3><ul><li><Mail/><span>Email<b>martina.russo@email.it</b></span></li><li><Phone/><span>Telefono<b>+39 333 456 7890</b></span></li><li><CalendarDays/><span>Anno di nascita<b>1998</b></span></li><li><MapPin/><span>Luogo di nascita<b>Milano</b></span></li><li><Languages/><span>Lingue<b>Italiano, Inglese B2</b></span></li></ul></article>
    <article className="panel skills-card"><p className="eyebrow">Dal curriculum</p><h3>Competenze</h3><div><span>Vendita assistita</span><span>Visual merchandising</span><span>Gestione cassa</span><span>Microsoft Office</span></div></article>
  </aside></section>
</AppShell>}
